FROM flink:1.18-scala_2.12-java11

COPY flink-lib/flink-sql-connector-kafka-3.1.0-1.18.jar /opt/flink/lib/
COPY flink-lib/flink-connector-jdbc-3.1.2-1.18.jar /opt/flink/lib/
COPY flink-lib/mysql-connector-j-8.3.0.jar /opt/flink/lib/
COPY flink-lib/flink-sql-connector-mysql-cdc-3.2.1.jar /opt/flink/lib/
COPY flink-lib/flink-statebackend-rocksdb-1.18.1.jar /opt/flink/lib/
COPY flink-lib/frocksdbjni-6.20.3-ververica-2.0.jar /opt/flink/lib/
COPY flink-lib/flink-metrics-prometheus-1.18.1.jar /opt/flink/lib/
